In [8]:
import pandas as pd

In [9]:
df = pd.read_csv('titanic.csv')

In [10]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
df.iloc[:,:2].head()

   PassengerId  Survived
0            1         0
1            2         1
2            3         1
3            4         1
4            5         0

In [12]:
df.iloc[0].head()

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Name: 0, dtype: object

In [13]:
df.iloc[:,4:].head()

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S
1  female  38.0      1      0          PC 17599  71.2833   C85        C
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
3  female  35.0      1      0            113803  53.1000  C123        S
4    male  35.0      0      0            373450   8.0500   NaN        S

In [14]:
df.drop('Name' , axis=1).head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [96]:
newdf = df[['Embarked','Pclass' ,'Fare']]
newdf

    Embarked  Pclass     Fare
0          S       3   7.2500
1          C       1  71.2833
2          S       3   7.9250
3          S       1  53.1000
4          S       3   8.0500
..       ...     ...      ...
886        S       2  13.0000
887        S       1  30.0000
888        S       3  23.4500
889        C       1  30.0000
890        Q       3   7.7500

[891 rows x 3 columns]

In [97]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
newdf.loc[:, 'Embarked'] = le.fit_transform(newdf['Embarked'])
newdf['Embarked']

0      2
1      0
2      2
3      2
4      2
      ..
886    2
887    2
888    2
889    0
890    1
Name: Embarked, Length: 891, dtype: object

In [99]:
from sklearn.model_selection import train_test_split
x = newdf[['Embarked','Pclass']]
y = newdf['Fare'] 
x_train ,x_test ,y_train ,y_test  = train_test_split(x, y ,test_size = 0.2)

In [100]:
x_train.shape
y_train.shape

(712,)

In [101]:
x_test.shape
y_test.shape

(179,)

In [107]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
newdf.loc[:, 'Embarked'] = le.fit_transform(newdf['Embarked'])
newdf['Embarked']

0      2
1      0
2      2
3      2
4      2
      ..
886    2
887    2
888    2
889    0
890    1
Name: Embarked, Length: 891, dtype: object

In [108]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [109]:
x_train_scaled.shape , x_test_scaled

((712, 2),
 array([[-1.96602441, -1.57790008],
        [ 0.57677192, -1.57790008],
        [-1.96602441, -1.57790008],
        [ 0.57677192,  0.8252333 ],
        [-0.69462624,  0.8252333 ],
        [ 0.57677192, -0.37633339],
        [-1.96602441, -1.57790008],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -1.57790008],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -1.57790008],
        [ 0.57677192, -0.37633339],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [-1.96602441, -1.57790008],
        [ 0.57677192, -0.37633339],
        [ 0.57677192, -1.57790008],
        [-0.69462624,  0.8252333 ],
        [-1.96602441,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -0.37633339],
        [ 0.57677192,  0.8252333 ],
        [-0.69462624,  0.8252333 ],
        [ 0.57677192, -1.57790008],
        [-1.96602441, -1.57790008],
        [-0.69462624,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [-1.96602441, -1.57790008],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -0.37633339],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -0.37633339],
        [-1.96602441, -1.57790008],
        [-0.69462624,  0.8252333 ],
        [-0.69462624,  0.8252333 ],
        [ 0.57677192, -1.57790008],
        [ 0.57677192,  0.8252333 ],
        [-1.96602441, -1.57790008],
        [ 0.57677192,  0.8252333 ],
        [-1.96602441, -1.57790008],
        [ 0.57677192, -1.57790008],
        [-1.96602441, -1.57790008],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -0.37633339],
        [-1.96602441, -0.37633339],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -1.57790008],
        [ 0.57677192,  0.8252333 ],
        [-0.69462624,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -0.37633339],
        [ 0.57677192, -0.37633339],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [-1.96602441,  0.8252333 ],
        [-1.96602441, -1.57790008],
        [-1.96602441, -1.57790008],
        [ 0.57677192, -0.37633339],
        [-0.69462624,  0.8252333 ],
        [-1.96602441,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -0.37633339],
        [ 0.57677192, -1.57790008],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [-0.69462624,  0.8252333 ],
        [ 0.57677192, -0.37633339],
        [-0.69462624,  0.8252333 ],
        [-1.96602441,  0.8252333 ],
        [ 0.57677192, -0.37633339],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -0.37633339],
        [-1.96602441, -1.57790008],
        [ 0.57677192, -0.37633339],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -0.37633339],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -0.37633339],
        [ 0.57677192, -0.37633339],
        [ 0.57677192, -0.37633339],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -0.37633339],
        [-1.96602441,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -1.57790008],
        [-1.96602441, -1.57790008],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -0.37633339],
        [-1.96602441, -0.37633339],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [-1.96602441, -1.57790008],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -0.37633339],
        [ 0.57677192,  0.8252333 ],
        [-1.96602441,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -1.57790008],
        [-0.69462624,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -1.57790008],
        [ 0.57677192, -0.37633339],
        [-1.96602441, -1.57790008],
        [ 0.57677192, -1.57790008],
        [-1.96602441, -0.37633339],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -0.37633339],
        [-1.96602441, -1.57790008],
        [ 0.57677192, -1.57790008],
        [-1.96602441, -1.57790008],
        [-1.96602441,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [-1.96602441,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [-0.69462624, -0.37633339],
        [ 0.57677192,  0.8252333 ],
        [-1.96602441, -1.57790008],
        [ 0.57677192, -0.37633339],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -0.37633339],
        [-1.96602441,  0.8252333 ],
        [-1.96602441,  0.8252333 ],
        [ 0.57677192, -0.37633339],
        [ 1.84817009, -1.57790008],
        [ 0.57677192, -1.57790008],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [-1.96602441,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -0.37633339],
        [ 0.57677192, -1.57790008],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -0.37633339],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -1.57790008],
        [ 0.57677192,  0.8252333 ],
        [-0.69462624,  0.8252333 ],
        [-1.96602441, -1.57790008],
        [ 0.57677192, -1.57790008],
        [ 0.57677192,  0.8252333 ],
        [-1.96602441, -1.57790008],
        [ 0.57677192, -1.57790008],
        [ 0.57677192,  0.8252333 ],
        [-0.69462624,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192, -1.57790008],
        [ 0.57677192, -0.37633339],
        [ 0.57677192, -1.57790008],
        [-1.96602441, -1.57790008],
        [ 0.57677192, -1.57790008],
        [ 0.57677192,  0.8252333 ],
        [-1.96602441, -1.57790008],
        [ 0.57677192, -0.37633339],
        [ 0.57677192,  0.8252333 ],
        [ 0.57677192,  0.8252333 ],
        [-0.69462624,  0.8252333 ]]))

In [110]:
x_train_scaled = pd.DataFrame(x_train_scaled , columns = x_train.columns)
x_test_scaled = pd.DataFrame(x_test_scaled , columns = x_test.columns)

In [117]:
x_train_scaled

     Embarked    Pclass
0   -0.694626  0.825233
1   -1.966024 -1.577900
2   -1.966024 -0.376333
3    0.576772  0.825233
4    0.576772 -0.376333
..        ...       ...
707  0.576772  0.825233
708  0.576772 -0.376333
709 -1.966024 -1.577900
710  0.576772 -0.376333
711  0.576772  0.825233

[712 rows x 2 columns]

In [124]:
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor(n_neighbors=5)  # you can tune n_neighbors
knn.fit(x_train_scaled, y_train)

KNeighborsRegressor()

In [130]:
# Predictions
y_pred = knn.predict(x_test_scaled)
y_pred

array([74.13582, 72.85084, 74.13582,  9.24916,  9.11418, 23.15   ,
       74.13582,  9.24916, 72.85084,  9.24916,  9.24916, 72.85084,
       23.15   ,  9.24916,  9.24916,  9.24916, 74.13582, 23.15   ,
       72.85084,  9.11418,  8.59834,  9.24916, 23.15   ,  9.24916,
        9.11418, 72.85084, 74.13582,  9.11418,  9.24916,  9.24916,
       74.13582,  9.24916,  9.24916, 23.15   ,  9.24916, 23.15   ,
       74.13582,  9.11418,  9.11418, 72.85084,  9.24916, 74.13582,
        9.24916, 74.13582, 72.85084, 74.13582,  9.24916, 23.15   ,
       27.275  ,  9.24916,  9.24916, 72.85084,  9.24916,  9.11418,
        9.24916, 23.15   , 23.15   ,  9.24916,  9.24916,  8.59834,
       74.13582, 74.13582, 23.15   ,  9.11418,  8.59834,  9.24916,
        9.24916, 23.15   , 72.85084,  9.24916,  9.24916,  9.11418,
       23.15   ,  9.11418,  8.59834, 23.15   ,  9.24916,  9.24916,
        9.24916, 23.15   , 74.13582, 23.15   ,  9.24916,  9.24916,
        9.24916, 23.15   ,  9.24916,  9.24916, 23.15   , 23.15   ,
       23.15   ,  9.24916, 23.15   ,  8.59834,  9.24916,  9.24916,
        9.24916, 72.85084, 74.13582,  9.24916,  9.24916, 23.15   ,
       27.275  ,  9.24916,  9.24916,  9.24916,  9.24916,  9.24916,
        9.24916,  9.24916,  9.24916,  9.24916, 74.13582,  9.24916,
       23.15   ,  9.24916,  8.59834,  9.24916,  9.24916, 72.85084,
        9.11418,  9.24916, 72.85084, 23.15   , 74.13582, 72.85084,
       27.275  ,  9.24916, 23.15   , 74.13582, 72.85084, 74.13582,
        8.59834,  9.24916,  8.59834,  9.24916, 10.93834,  9.24916,
       74.13582, 23.15   ,  9.24916, 23.15   ,  8.59834,  8.59834,
       23.15   , 89.07418, 72.85084,  9.24916,  9.24916,  8.59834,
        9.24916, 23.15   , 72.85084,  9.24916, 23.15   ,  9.24916,
       72.85084,  9.24916,  9.11418, 74.13582, 72.85084,  9.24916,
       74.13582, 72.85084,  9.24916,  9.11418,  9.24916,  9.24916,
       72.85084, 23.15   , 72.85084, 74.13582, 72.85084,  9.24916,
       74.13582, 23.15   ,  9.24916,  9.24916,  9.11418])