In [125]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer ,SimpleImputer
from sklearn.linear_model import LogisticRegression


from sklearn.metrics import accuracy_score

In [126]:
df = pd.read_csv("titanic.csv")[['Age','Pclass','Fare','Survived']]

In [127]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [128]:
df.isnull().mean() *100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [129]:
x = df.drop(columns = ['Survived'])
y = df['Survived']

In [141]:
X_train ,X_test ,y_train, y_test  = train_test_split(x,y, test_size = 0.2 ,random_state = 42)

In [142]:
X_train.shape , X_test.shape

((712, 3), (179, 3))

In [143]:
knn  = KNNImputer(n_neighbors=5 ,weights='distance')

X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [133]:
X_train_trf

array([[45.5       ,  3.        ,  7.225     ],
       [40.4       ,  2.        ,  0.        ],
       [21.        ,  1.        , 77.2875    ],
       ...,
       [17.        ,  2.        , 10.5       ],
       [19.70662149,  3.        , 22.3583    ],
       [28.6       ,  3.        ,  7.8958    ]])

In [134]:
pd.DataFrame(X_train_trf ,columns = X_train.columns)

           Age  Pclass     Fare
0    45.500000     3.0   7.2250
1    40.400000     2.0   0.0000
2    21.000000     1.0  77.2875
3    24.000000     2.0  13.0000
4    28.000000     3.0   7.8958
..         ...     ...      ...
707  34.800000     3.0   7.2500
708  23.000000     2.0  11.5000
709  17.000000     2.0  10.5000
710  19.706621     3.0  22.3583
711  28.600000     3.0   7.8958

[712 rows x 3 columns]

In [144]:
lr = LogisticRegression()

lr.fit(X_train_trf ,y_train)

y_pred = lr.predict(X_test_trf)

accuracy_score(y_test,y_pred)

0.7430167597765364