# titanic dataset me predict karenge or pipelines use krna seekhenge

## plan

# 1 missing values theek karenge

# 2 OHE on sex and embarked

# 3 Scaling

# 4 feature selection

# 5 model training

In [3]:
import pandas as pd
import numpy as np

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.tree import DecisionTreeClassifier

In [5]:
df = pd.read_csv('titanic.csv')

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df.drop(columns = ['PassengerId', 'Name', 'Ticket' , 'Cabin'],inplace = True)
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [9]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [79]:
X_train ,X_test ,y_train , y_test = train_test_split( df.drop(columns = ['Survived']),
                                                       df['Survived']  ,
                                                       test_size = 0.2 ,
                                                       random_state = 42)

In [80]:
X_train.shape ,X_test.shape

((712, 7), (179, 7))

In [81]:
y_train.shape, y_test.shape

((712,), (179,))

In [82]:
# step --> 1
# missing values theek karenge
# imputation transformer

In [17]:
trf1 = ColumnTransformer([
    ('impute_age', SimpleImputer(),[2]),
    ('impute_embarked', SimpleImputer(strategy = 'most_frequent'),[7])
],remainder = 'passthrough')

In [19]:
trf2 = ColumnTransformer([
    ('ohe_sex_embarked', OneHotEncoder(sparse_output = False,drop = 'first'),[2,7])
],remainder = 'passthrough')

In [22]:
trf3 = ColumnTransformer([
    ('scaler',MinMaxScaler(),slice(0,7))
])

In [23]:
# Feature selection
trf4 = SelectKBest(score_func=chi2,k=7)

In [24]:
# train the model
trf5 = DecisionTreeClassifier()

In [25]:
pipe = Pipeline([
    ('trf1',trf1),
    ('trf2',trf2),
    ('trf3',trf3),
    ('trf4',trf4),
    ('trf5',trf5)
])