In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

In [6]:
df = pd.read_csv('titanic_toy.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Age       714 non-null    float64
 1   Fare      846 non-null    float64
 2   Family    891 non-null    int64
 3   Survived  891 non-null    int64
dtypes: float64(2), int64(2)
memory usage: 28.0 KB

In [47]:
df.tail()

      Age   Fare  Survived
886  27.0  13.00         0
887  19.0  30.00         1
888   NaN  23.45         0
889  26.0    NaN         1
890  32.0   7.75         0

In [7]:
df.isnull().sum()

Age         177
Fare         45
Family        0
Survived      0
dtype: int64

In [9]:
df.isnull().mean()*100

Age         19.865320
Fare         5.050505
Family       0.000000
Survived     0.000000
dtype: float64

In [18]:
df = df.drop(df.columns[[2]],axis = 1)

In [19]:
df.head()

    Age     Fare  Survived
0  22.0   7.2500         0
1  38.0  71.2833         1
3  35.0  53.1000         1
4  35.0   8.0500         0
5   NaN   8.4583         0

In [22]:
x = df.drop(columns = ['Survived'])
y = df['Survived']

In [23]:
X_train ,X_test,y_train ,y_test = train_test_split(x,y, test_size = 0.2,random_state = 2)

In [24]:
X_train.shape ,X_test.shape

((712, 2), (178, 2))

In [42]:
# isse kya kua na ki age col me jitne
# bhi na the unke liye sample random values apan ne bana li
# lekin ab un na vlaues ko ye ranodm val assign karni hai



random_ages = X_train['Age'].dropna().sample(X_train['Age'].isnull().sum()).values

In [43]:
nan_indexes = X_train['Age'][X_train['Age'].isnull()].index

In [44]:
X_train.loc[nan_indexes , 'Age'] = random_ages

In [46]:
X_train['Age'].isnull().sum()

np.int64(0)